### ISSUE TITLE
File encoding caribbean_14C.csv

### ISSUE THREAD

**Issue by nevrome** [philriris/caribbean-14C#1]
Hey @philriris - thanks for preparing this dataset! 

Do you think it might be possible to change the file encoding to the more common UTF-8, though? This would certainly increase the ease of reuse.

**Comment by philriris** [comment]
Thanks for flagging - this has been resolved now.

**Comment by nevrome** [comment]
Thank you very much! The database [will soon be](https://github.com/ropensci/c14bazAAR/pull/138) available via c14bazAAR :+1:
